[ui]
paginate = "never"
default-command = ["log", "--limit=10"]
show-cryptographic-signatures = false

[aliases]
pr-fetch = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
jj git fetch
jj bookmark track ${1}@origin
jj edit ${1}
""", ""]
