[ui]
paginate = "never"
default-command = ["log", "--limit=10"]
show-cryptographic-signatures = false

[aliases]
pr-fetch = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
jj git fetch
jj bookmark track ${1}@origin
jj new ${1}
""", ""]
pr = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
BRANCH="$(jj bookmark list --revisions @ --template 'name')"
TEMPLATE=""
[ -f .github/pull_request_template.md ] && TEMPLATE="--template pull_request_template.md"
gh pr create --head $BRANCH --draft $TEMPLATE --editor
""", ""]
